DROP TABLE EMP_ROLE;
DROP TABLE ROLE;
DROP TABLE CONTACT;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
ID SERIAL		NOT NULL,
FIRST_NAME	VARCHAR(250)	DEFAULT NULL,
MIDDLE_NAME	VARCHAR(250)	DEFAULT NULL,
LAST_NAME 	VARCHAR(250)	DEFAULT NULL,
SUFFIX			VARCHAR(50)		DEFAULT NULL,
TITLE				VARCHAR(50)		DEFAULT NULL,
STREET_NO		VARCHAR(50)		DEFAULT NULL,
BRGY				VARCHAR(50)		DEFAULT NULL,
CITY_MUNICIPALITY VARCHAR(250)	DEFAULT NULL,
ZIPCODE			VARCHAR(50) 	DEFAULT NULL,
BIRTHDAY		DATE,
HIRE_DATE		DATE,
GWA					REAL,
IS_EMPLOYED	BOOLEAN,
PRIMARY KEY (ID)
);
CREATE TABLE CONTACT(
ID	SERIAL	NOT NULL,
CONTACT_TYPE		VARCHAR(250)	DEFAULT NULL,
CONTACT_DETAILS	VARCHAR(250)	DEFAULT NULL,
EMPLOYEE_ID	INT DEFAULT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE EMP_ROLE(
EMPLOYEE_ID INT NOT NULL,
ROLE_ID			INT NOT NULL,
PRIMARY KEY (EMPLOYEE_ID, ROLE_ID)
);
CREATE TABLE ROLE(
ID	SERIAL	NOT NULL,
ROLE_NAME	VARCHAR(250) NOT NULL,
PRIMARY KEY (ID)
);
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (1,'Quality Assurance Engineer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (2,'Software Developer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (3,'Infrastructure Engineer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (4,'Finance Officer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (5,'Human Resources Officer');
