DROP TABLE EMPLOYEE_ROLE;
DROP TABLE ROLE;
DROP TABLE CONTACT;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
ID INT NOT NULL,
FIRST_NAME	VARCHAR(250)	DEFAULT NULL,
MIDDLE_NAME	VARCHAR(250)	DEFAULT NULL,
LAST_NAME 	VARCHAR(250)	DEFAULT NULL,
SUFFIX			VARCHAR(50)		DEFAULT NULL,
TITLE				VARCHAR(50)		DEFAULT NULL,
STREET_NO		VARCHAR(50)		DEFAULT NULL,
BRGY				VARCHAR(50)		DEFAULT NULL,
CITY_MUNICIPALITY VARCHAR(250)	DEFAULT NULL,
ZIPCODE			VARCHAR(50) 	DEFAULT NULL,
BIRTHDAY		DATE,
HIRE_DATE		DATE,
GWA					REAL,
IS_EMPLOYED	BOOLEAN,
CONSTRAINT PERSON_PK PRIMARY KEY (ID)
);
CREATE TABLE CONTACT(
ID	INT	NOT NULL,
CONTACT_TYPE		VARCHAR(250)	NOT NULL,
CONTACT_DETAILS	VARCHAR(250)	NOT NULL,
EMPLOYEE_ID	INT DEFAULT NULL,
CONSTRAINT CONTACT_PK PRIMARY KEY (ID),
CONSTRAINT EMPLOYEE_ID_FK FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);
CREATE TABLE ROLE(
ID	INT	NOT NULL,
ROLE_NAME	VARCHAR(250) NOT NULL,
CONSTRAINT ROLE_PK PRIMARY KEY (ID)
);
CREATE TABLE EMPLOYEE_ROLE(
EMPLOYEE_ID INT NOT NULL,
ROLE_ID			INT NOT NULL,
CONSTRAINT EMPLOYEE_ID_FK FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEE(ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT ROLE_ID_FK FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (1,'Quality Assurance Engineer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (2,'Software Developer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (3,'Infrastructure Engineer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (4,'Finance Officer');
INSERT INTO ROLE (ID, ROLE_NAME) VALUES (5,'Human Resources Officer');
